sudo: required
language: generic
services:
- docker
env:
  matrix:
  - MYSQL_VERSION="5.7"
  - MYSQL_VERSION="8.0"
  global:
  - secure: OXYbwi5LwQAzansIF8B0nxhFXgGDMunk/LJ5O5kOjTGwn1AbD9aN4T7txX695yHO2TpFEXsgsh5Tg86EZwb6jEJ5Tz6gKgOzLaTy6dT80ARym6+GYP4Dp+oy3PrsvqfaCF8R6U2ff8piqmJsV14Cbubb6dEyB8Rv16x2aIZkRq003duFlJFHrddBd5FxaKeAnpeMwJHFj+2MgK0AfHjV0yIrT/o/JGlzP9n+AYVtH4W80U0bwfxEqmFKiGojMCxDk9tds87a+WNCh+uu3bYGDw+ZiROBypaEzQZ/haeVWdli8FvNH/NrJKQGQD1KSFisqf0JztlnmLtBOg7jrLZhaOHB2VQrQYgFfa0oaFu1RMdoWsEi1R+zwa3iZN5+j3/6MA3BaP4KWx4ySiPImI95UZTL31w6QLVzPGDfGHQt0SD678IKEQq3YspWbqlMeVEYFaQGVKlvWZB63EgMB4IQ9yC6zgXSJNgqTmMUmgYI478+ZNIhm/4jUbT59LSqAUrs3XEQGgfGzSKoCFc9SBV+tejY7ZAhFSWNsE/cY/kg1SwKEVrNmqaXbz/fc5B3yzGnHLti26inRnPR8PRwGS5e1QIclmcL/rNBSC7hj9eyZmoiJ9MJGpfx4eaFXvOoSdgbfcwOrF3Dtcq7jT5NUoU6lRulCZNbdJ3wosNfgOmF3Nw=
  - secure: druhTzeE4TLllR1FAn1r8yUDviwU2Np78gW9/izJQCHa1f8M/0DBqkzHKXwL+sWTyqqAKgpliAwNo7uOjMr13ENSfEhKOrRVeI/5cS2OIxMCcDf5SAs5brw4yRK0sS8A0JzPVsnG2c/A68wOrpLRr1AdHt+WgpPLIXuNpv3NgP43mJrOsrswK23gndW5Q7n8uaoR7tOYCaL6c3HzWdp1EFg23NFVuw73h5w4h5Fzs3rIVebhBq+0eV9CJyQorZodX5B+O7I4KnXbbeMB0s+Xvb9rqwZY5ld6ozNU/WkjeBZJx0ZGbvAWN/aBpmP5eDE1s8TX9pNhc0pzsx2fCXYAODml0g0vYrGy5ar+vpwj02h9ysd1ZOKhk1swUN9zs0dP99ooYMD1dPzjk/QWjnJSMQdsNbzBQoYPsNydKpypdHl0UC0UD5YfQMrWxdWTFTvjKBgPwiEGH41M24Hcir0iY+nBt2DiKHZraROcly41zgT/XlOMMNITlTlg8AU00wKHFGkXDi3v7n4RGUhJd/uFs064m6Jp99d983EwfqI6X3lR3jg22MDw5VQ7Q8lencNfulzXUuZkWILB0+hexVcWiV0BsFxnxrkswqbIkmntmnqAYlT6YAMgF2/mgNhYxJoFL3Qa0Yxxsdw+TGt161AkoBBJDbRFskQoqEXI4RiomKE=
script:
- "./build-and-test.sh"
- docker images | grep thecodingmachine/mysql
- |
  if [[ "$TRAVIS_PULL_REQUEST" = false && "$TRAVIS_BRANCH" = "master" ]] ; then
    docker login -u $DOCKER_USER -p $DOCKER_PASS
    docker push thecodingmachine/mysql:${MYSQL_VERSION}-v1
  fi
