sudo: required
language: generic
services:
- docker
env:
  matrix:
  - MYSQL_VERSION="5.7"
  - MYSQL_VERSION="8.0"
  global:
  - secure: CnjRGZw1oDOH0DMq4VMdxJJL2SHxxIbPJwvWZ4+jEYQza5rpmmFVjtSI0bG21i5yII3R0ju+visK54MRwBjJhJOeLAe99vlUiGxloO9c835we+fAEvAwpcv/xxYqcoTUSwkdLmXRipZvz2LUiupbZxDsmAJGmMYbb9iFtKWGSufEqgzOH59ENcREy2RaOrg0e1hWs6AppJTPhpahqbcGG1tTs+iuLg8Vbuln/2L/RcZXMfoTBQTXrn8M7yctR4n2sknfg6I8f1oyirvnYWwrsTLL3YtJ3PwFebDMTjJvUz4VDWXzGK+WYKO+DLkiMFD07c5IoU3+FufRwwFL5b8Ec6dvxW3CmMorOlPiKy/Kz5cdCqeNZylFuylqySesgNauuW2gvDvW2hJZXHXtVJ/wJ1oUp/3fdRNbYsp3EBnD4GUWwQf3qLL6uLzo+ABa6XsVwUOQLDaWd4KFCgphhvDIwMPBozGLwLUPKXRldBi7lxrjQ3LWPMdxXPsinzAtQiOKBzR8Bd5xry9hqWucZ4fXyjUdAHldgKs3SiUJncxjfgtY427uNCfYZBNrwYb6QPL+fyzSNGyWeUrxEe6Dg4GaYqNZ2F7yc2yLmmb7wXXJGIIzrw6eaBc801h1FlX1/vZ8oQqtpfU3lxhJhaVxsaH1gi0DT3ckwggn1fg166bfJFg=
  - secure: S3a3xUhh1EpLxy04QsQPpcdz28nAJaO1yPXW4K0vWls9dpJLpgIfpys0RB+mkpN1oJ0khd/Kd0KV3HExqC0XWOU0TI1lKvZotkmNiTiC4aRoRt5R4AIpXE+19iFmQQyzqjeZO+TnVMygL6t3afJMYMEGAAl2yQjt9mbYeBS4Vlor/wNDxZhje+ZtMECFb0OUeFn7nktMu7TMg9uBLWcTy8BCEn8K4au6lUvOe5Qaap5HS09AUn4/1QptJ6KKP3cODuD+kh5+fb+kzNHRjor0yXOMvD2r93qrWYtDFGDFWbbqFny03LunBlzFA4tLw1MXkLmEKoGgUavV11ZRLtrjpw0x+Zb1KU2WUKkzht90HgitGf6airiLFr8edPEwfSFFGuZ9ezvKcp0+QeNm4narZvcWjPL40ge1cxbcdpnrF5zteW6w0XrDMqLc2l7jtxZsOK16RvDDCBMriw6Eer+fT3g8HbL8G177Os28H2NyueVpVKpSDH0N5f1Z/xstd0KvkZkzX3oGQxYaaYBkA92/9tE/Bd0BksrgrjmHQPu5B0cbi1p04u1xraK7NgWl20D3IyNZ9emugOD4uMAgoZ7lDSO1dMcZYnsQnDaxhltpwuNIgrm6Ck/xaehKpkqo/rkAOPPDIvZtWuhF9BPYzTY3rnX6+SpDmDbqG7Z0+lp2nOE=
script:
- "./build-and-test.sh"
- docker images | grep thecodingmachine/mysql
- |
  if [[ "$TRAVIS_PULL_REQUEST" = false && "$TRAVIS_BRANCH" = "master" ]] ; then
    echo $DOCKER_USER
    docker login -u $DOCKER_USER -p $DOCKER_PASS
    docker push thecodingmachine/mysql:${MYSQL_VERSION}-v1
  fi
